"""Turn a plain-English brief into a spec.

Scope drift is the metric that catches an agent building the wrong thing —
and it was gated behind hand-authoring YAML, which is why nobody reached it.

A user already knows what they asked the agent for; they typed it once
already. This converts that text into the spec, transparently and without
a model: one feature per line or bullet, slugged into an id. The result is
written to disk so it can be read, corrected, and version-controlled — it
is a starting point the user owns, not a hidden inference.
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml

_BULLET = re.compile(r"^\s*(?:[-*•]|\d+[.)])\s*")
_NON_WORD = re.compile(r"[^a-z0-9]+")

# Words that carry no meaning in an identifier.
_STOP = {
    "a", "an", "the", "and", "or", "to", "for", "of", "with", "that", "this",
    "can", "should", "must", "will", "be", "is", "are", "it", "user", "users",
    "able", "allow", "allows", "add", "adds", "build", "create", "make",
    "support", "supports", "implement", "implements", "please", "want", "need",
}


def slugify(text: str, fallback: str) -> str:
    """"Users can log in with email" -> "log.in.email"."""
    words = [w for w in _NON_WORD.sub(" ", text.lower()).split() if w and w not in _STOP]
    return ".".join(words[:3]) if words else fallback


def parse_brief(brief: str) -> list[dict[str, str]]:
    """Split a brief into one feature per line or bullet."""
    features: list[dict[str, str]] = []
    seen: set[str] = set()
    for raw in brief.splitlines():
        line = _BULLET.sub("", raw).strip().rstrip(".;,")
        if len(line) < 3:
            continue
        base = slugify(line, f"feature.{len(features) + 1}")
        fid, n = base, 2
        while fid in seen:
            fid, n = f"{base}.{n}", n + 1
        seen.add(fid)
        features.append({"id": fid, "description": line})
    return features


def build_spec(brief: str, name: str = "live_session") -> dict:
    """A complete, valid spec derived from the brief."""
    return {
        "name": name,
        "version": "1.0.0",
        "_derived_from_brief": True,
        "features": parse_brief(brief),
        "governance": [
            {"rule": "no_secrets_in_source",
             "description": "No credentials, keys or tokens committed to the repo."},
        ],
        "allowlist": {"external_apis": []},
    }


def spec_path_for(project: Path) -> Path:
    return Path(project) / ".auditor" / "spec.yaml"


def save_spec(project: Path, spec: dict) -> Path:
    """Write the spec where the user can find and edit it."""
    path = spec_path_for(project)
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Generated by `auditor live` from the brief you typed.\n"
        "# This is yours to edit — it is the definition of 'what was asked for',\n"
        "# and every scope-drift finding is measured against it.\n"
    )
    path.write_text(header + yaml.safe_dump(spec, sort_keys=False))
    return path


def load_spec(project: Path) -> dict | None:
    """Any spec already present for this project."""
    path = spec_path_for(project)
    if path.exists():
        try:
            return yaml.safe_load(path.read_text())
        except yaml.YAMLError:
            return None
    return None
